export global Theme {
    out property <brush> window-background: #000000;
    out property <brush> background-regular: #1C1C1E;
    out property <brush> border: #444446;
    out property <brush> foreground: #FFFFFF;
    out property <brush> heating-active: #34C759;
    out property <brush> heating-cold: @linear-gradient(20deg, #3C5584 0%, #04030F 100%);
    out property <brush> heating-warm: @linear-gradient(20deg, #A24E64 0%, #04030F 100%);
}
